language: ruby
# cache: bundler

addons:
  apt:
    packages:
      - imagemagick
      - libmagickwand-dev
      - qt5-default
      - libqt5webkit5-dev
      - xvfb
  artifacts:
    s3_region: "us-east-1"
    paths:
      - test-plans/report.html

rvm:
  - 2.3.3

install:
  - gem install bundler:1.15.4
  - bundle install

script:
  - printenv
  - pwd
  - rename 's/.example//' config/settings/*.example
  - cat config/settings/test.yml
  - rename 's/.example//' config/*.example
  - cat config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate db:seed
  - mkdir test-plans
  - xvfb-run -a bundle exec cucumber --format html --out test-plans/report.html

before_script:
  - mysql -e 'CREATE DATABASE mycloud_test;'

after_script:
  - ls test-plans

services:
  - mysql
  - redis-server

notifications:
  email: false

branches:
  only:
    - develop